PROD-86: fix email confirmation and views
sashamuliar/ProDobro pull request #28
Opened 2018-04-17 12:39 UTC by anastasiabalaban

# Reviewers

- [x] @vikabelous
- [x] @okohuch
- [x] @shevchukm 
- [x] @Pavliv

# Jira task

http://ssu-jira.softserveinc.com/browse/PROD-86

# Description

- add asserts to public folder
- add necessary configs to production
- change views with gem simple_form
- add flash messages

# Checklist:

- [x] Rubocop doesn't raise any warnings and offenses
- [x] PR is approved by 2 team mates
- [x] PR is approved by 2 experts

2018-04-17 13:14 UTC, Pavliv commented on app/views/devise/passwords/edit.html.haml
> +          = f.input :password, label: t('.new_password'), autofocus: true, autocomplete: "off", input_html: { class: 'form-control', minlength: 6 }, label: false
Use ' ' instead " "

2018-04-17 13:14 UTC, Pavliv commented on app/views/devise/passwords/edit.html.haml
> +          = f.input :password_confirmation, label: t('.confirm_new_password'), autocomplete: "off", input_html: { class: 'form-control' }
The same here

2018-04-17 13:14 UTC, Pavliv commented on app/views/devise/passwords/edit.html.haml
> +          = f.submit t('.change_my_password'), class: "btn btn-outline-info btn-size"
And here

2018-04-17 13:14 UTC, Pavliv commented on app/views/devise/shared/_links.html.haml
> +    = link_to t('.sign_in_with_provider', provider: OmniAuth::Utils.camelize(provider)), omniauth_authorize_path(resource_name, provider), class: "link"
Replace " " to ' '

2018-04-17 13:14 UTC, Pavliv commented on app/views/layouts/application.html.haml
> +            #{message}
The same

2018-04-17 13:54 UTC, Pavliv approved these changes

2018-04-17 14:00 UTC, shevchukm approved these changes

2018-04-17 17:56 UTC, viktoriia-bilous requested changes

2018-04-17 17:56 UTC, vikabelous commented on config/initializers/devise.rb
> +  config.secret_key = '9c72504bb7fca71b425dc1b89c429f405643ab21e035315b42330daadcf1a47fd5fd3583971bd6560c5be934ece2d7fbae7343b58d56f4c72a7369e934573132'
This value should be stored as ENV variable as well

2018-04-17 17:56 UTC, vikabelous commented on config/initializers/simple_form.rb
> +    ## full_messages_for
Please review this file and either remove unused settings with their comments or uncomment those settings you would like to use.

2018-04-17 17:56 UTC, vikabelous commented on public/assets/.sprockets-manifest-413d41b33cf339d3ef4b4c35f32e8402.json
> +{"files":{"email-d6b8be8bae4f838685f2f88e112702f4fef0e9c169d4ca25d52bcb14fdf7bb3b.css":{"logical_path":"email.css","mtime":"2018-04-12T16:39:15+03:00","size":437,"digest":"d6b8be8bae4f838685f2f88e112
`public/assets` folder should be in` .gitignor`
Assets should be compiled during the deploy process

2018-04-17 19:36 UTC, vikabelous commented on config/locales/simple_form.en.yml
> +    # Examples
Please delete unnecessary comments

2018-04-18 08:09 UTC, okohuch approved these changes

2018-04-19 10:24 UTC, viktoriia-bilous requested changes

2018-04-19 10:24 UTC, viktoriia-bilous commented on app/views/devise/passwords/edit.html.haml
> +          = f.input :password, label: t('.new_password'), autofocus: true, autocomplete: 'off', input_html: { class: 'form-control', id: 'password1', minlength: 6 }, label: false
`label: t('.new_password')`
`label: false`

2018-04-19 10:24 UTC, viktoriia-bilous commented on app/assets/javascripts/users.js
> +window.onload = function () {
You need a tool like rubocop for js files. This file has some style issues. Consider any of these gems:
https://github.com/appfolio/eslint-rails
https://github.com/damian/jshint
https://github.com/mackuba/jslint_on_rails

Add a chosen gem, configure it, run, fix errors, add to CI script as well.

2018-04-19 12:50 UTC, viktoriia-bilous approved these changes
Good job :)

2018-04-19 13:02 UTC, merged